### PR TITLE
Feature/10 deployment model prevent overlap

### PR DESCRIPTION
**Pull request by wiomoc**

### CODE REVIEW

**Review by KuhnMn — COMMENTED** [review]
Looks good, one small thing I found was The top node is not part of the bounding box, which makes things strange when building top-to-bottom workflows
grafik
Is this necessary and easy to implement? If not ignore, if yes maybe change :)

**Comment by wiomoc** [comment]
I fixed the issue. The top-node was / is part of the bounding box. The problem was a shift weren't executed if both nodes were too close to each other on the x-axis

**Review by KuhnMn — CHANGES_REQUESTED** [review]
The complete model viewer looks kinda broken :/
grafik
When putting two nodes close to each other and showing both, they do not move but instead are locked in place, unable to be moved anywhere else.
Hiding also does not work, it only hides the connecting lines.
The only thing that moves is the small menu which should normally be close to the nodes.
grafik

**Review by lokmanfl — APPROVED** [review]
The overlap prevention works. Just a small idea: It would be more intuitive if the colliding object was moved into the opposite direction of where the collision happens. For example, if an object collides at the bottom of another object, it should move upwards.

**Review by KuhnMn — APPROVED** [review]
LGTM!

**Pull request merged**
